# Generated by Django 5.1.3 on 2025-05-23 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='download_count',
        ),
        migrations.AddField(
            model_name='song',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='song',
            name='size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
