# Generated by Django 5.1.3 on 2025-05-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_download_count_song_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
